//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deviceDetectWF.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("deviceDetectWF.Resources.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ©Juraj Grečnár, 2019.
        /// </summary>
        internal static string AboutCopyright {
            get {
                return ResourceManager.GetString("AboutCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version .
        /// </summary>
        internal static string AboutVersion {
            get {
                return ResourceManager.GetString("AboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj1wQWduSkRKTjRWQQ==.
        /// </summary>
        internal static string DeviceDetectWF {
            get {
                return ResourceManager.GetString("DeviceDetectWF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///HOWTO:
        ///
        /// 1. Use Listener menu to start logging device changes.
        /// 2. When listener is enabled, initial scan of devices will occur.
        /// 3. Any detected change will add new snapshot of device tree to side panel.
        /// 4. Select any other snapshot to see complete list of devices and compare with previous snap.
        ///
        ///Enjoy!.
        /// </summary>
        internal static string HowTo {
            get {
                return ResourceManager.GetString("HowTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADDED DEVICES.
        /// </summary>
        internal static string LogContentAdded {
            get {
                return ResourceManager.GetString("LogContentAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPLETE LIST OF DEVICES DETECTED.
        /// </summary>
        internal static string LogContentEverything {
            get {
                return ResourceManager.GetString("LogContentEverything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REMOVED DEVICES.
        /// </summary>
        internal static string LogContentRemoved {
            get {
                return ResourceManager.GetString("LogContentRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/sk-juroot/deviceDetectWF.
        /// </summary>
        internal static string OpenSourceURL {
            get {
                return ResourceManager.GetString("OpenSourceURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeviceDetectWF.
        /// </summary>
        internal static string ProgramTitle {
            get {
                return ResourceManager.GetString("ProgramTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown device.
        /// </summary>
        internal static string UnknownDevice {
            get {
                return ResourceManager.GetString("UnknownDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown ID.
        /// </summary>
        internal static string UnknownId {
            get {
                return ResourceManager.GetString("UnknownId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device change.
        /// </summary>
        internal static string WParam0x7 {
            get {
                return ResourceManager.GetString("WParam0x7", resourceCulture);
            }
        }
    }
}
